vim.cmd([[autocmd FileType * set formatoptions-=ro]])
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.expandtab = true
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.wrap = false
vim.opt.cursorline = true
vim.opt.scrolloff = 10
vim.opt.ignorecase = true
vim.opt.clipboard = "unnamedplus"
vim.o.mouse = "a"
vim.opt.ignorecase = true
vim.opt.smartcase = true
